Revert "Cleanup: add semicolon after PyObject_VAR_HEAD"
This reverts commit a01bcfa6366f893fbc8fdbf537d91ece4832ea03.

This causes MSVC2019 build to fail with error C2059

Unfortunately this means we have to put up with bad formatting
in Python structs.